### ISSUE TITLE
Upload to Flathub?

### ISSUE THREAD

**Issue by poperigby** [josecastillolema/org.freedesktop.Sdk.Extension.ocaml#1]
I've found your extension to be very useful. Is there any reason it isn't on Flathub?

**Comment by josecastillolema** [comment]
Thanks @poperigby,
the extension is being prepared for submission to Flathub.

**Comment by poperigby** [comment]
Awesome! :slightly_smiling_face:

**Comment by josecastillolema** [comment]
Done! https://github.com/flathub/org.freedesktop.Sdk.Extension.ocaml
